### ISSUE TITLE
Display target mismatch

### ISSUE THREAD

**Issue by joker-b** [sxrsdk/sxrsdk-demos#25]
I built everything from the default setup and found that while the monoscopic display is the default, that on startup the app still requested to be plugged into GearVR. I'm guessing that this is because it detects the oculus sig file I added to the resources?

In any case, the default apps now only run when inside a GearVR, but in monoscopic mode -- and when disconnected from the GearVR they exit. Hard to see.

**Comment by liaxim** [comment]
Please make sure you clone the latest release_v5.0 branch of the demos. We have build variants for monoscopic and the rest. In Android Studio go to "Build Variants" and pick the one you want. Monoscopic will no longer trigger the "plug into GearVR" prompt.

**Comment by liaxim** [comment]
Fixes have been merged.
