### ISSUE TITLE
After update, build fails on ":sxr_adapter-release:"

### ISSUE THREAD

**Issue by joker-b** [sxrsdk/sxrsdk-demos#38]
...even when build variants are set to debug versions, and after executing "clean project," gradle sync fails

Oddly, this was building successfully before the last pull -- the relase_5 zip appears to be trailing master and the release branch, do I need to rebuild the SDK from source? On which branch?

**Comment by joker-b** [comment]
nvm, for reasons I don't follow those aars were missing from my last d/l

**Comment by ragner** [comment]
I am facing the same issue 
Unable to resolve dependency for ':sxr-360photo@arDebug/compileClasspath': Could not find :sxr_adapter-release:.

How did you fix that?

**Comment by joker-b** [comment]
I re-downloaded the 5.0 release ZIP. As I mentioned, somehow I did not have the correct aar files for those specific functions. Perhaps there were two different editions of the SDK build at that time? I don't know how I would have deleted only those specific files by accident. Regardless, re-download and unpack the SXRSDK release-build ZIP. That fixed it for me.

**Comment by liaxim** [comment]
@ragner The sxr_adapter was missing from the archive so we had it updated. Also the release has been uploaded to maven so the zip is no longer necessary.
