### ISSUE TITLE
samples build but give error when run

### ISSUE THREAD

**Issue by SmilerOnline** [sxrsdk/sxrsdk-demos#53]
error: cannot find symbol class IApplicationEvents.
This occurs for both the monoscopicDebug and oculusDebug build variants when using Android Studio for building on Windows

**Comment by liaxim** [comment]
Please make sure you clean your repo (git clean -fdx) and force gradle to re-download the dependencies.

**Comment by liaxim** [comment]
@SmilerOnline Have verified that demos build off the maven snapshot and also when building the sxr sdk locally.
