### ISSUE TITLE
Branch release_v5.0 does not exist

### ISSUE THREAD

**Issue by joturako** [sxrsdk/sxrsdk-demos#7]
Hi there,
As in branch master README, the instructions is to download the repo with branch `release_v5.0` but it doesn't exist.

**Comment by thomasflynn** [comment]
heh, that's because you're beating us to the release by a couple days :).  We planning to announce the SXR SDK to the world on Wednesday.  in the meantime, we're scrambling to get the last couple of commits in and then we'll produce a 5.0 release and upload all the sdk binaries to maven.  At that point, all the demos here will compile and work.  So, I ask for a few more days of patience :)

May I ask how you found us?

**Comment by joturako** [comment]
Hello, actually I'm learning to do VR app with http://www.gearvrf.org framework.
Suddenly, after the weekend, instructions all changed to this new repos, and the API Reference here http://www.gearvrf.org/api_reference/ is broken, so I think you guy have a new release. Usually after everything is in place, you update the official site instructions but I think the process got reversed a little bit.

I migrated all the GVR to SXR apis but the build process failed because maven binaries doesn't exists. I was in process of setting up a private maven repo but hearing from you I will just wait till Wednesday.

Have a good day :)

**Comment by thomasflynn** [comment]
sorry, looks like someone pulled the trigger on the website too early.  And even when it was triggered, i expected the old gearvrf.org website to still be available.  i'll get it sorted out.

**Comment by thomasflynn** [comment]
ok, it looks like the gearvrf.org website is restored.

**Comment by joturako** [comment]
Thank you, it is indeed working now. Meanwhile, I ran the private repo of version 5.0 and needed to tweak the template a bit because of some missing .so files. If I ran into the same problem after the release I will create another issue ticket for them. But it's working fine for now.

PS: There are still some variables in the sdk as well as the demo that still have the word "gvr" instead of "sxr".

Have a good day :)

**Comment by thomasflynn** [comment]
ok.  thanks.
if it's just some variables that have 'gvr' in it, that's fine, we'll get to it eventually.  but there shouldn't be any APIs or packages with 'gvr' in them.

**Comment by spakanati123** [comment]
@thomasflynn all of sudden everything changed from gvr to sxr so what's all improvements or new features we can expect from this migration.

**Comment by thomasflynn** [comment]
gearvrf.org should be switched back to the correct site at this point.

The reason for the switch is a re-branding.  Too many thought GearVRf was limited to GearVR only.  But we also handle DayDream, monoscopic, and can do AR with ARCore and our MixedReality Extension.  We need to re-brand and get the word out.

The renaming in the code is the following:
package rename from: org.gearvrf to com.samsungxr
all classes and APIs changed their prefix from: GVR to SXR  (also helps alleviate confusion from DayDream who decided to prefix all their classes with GVR (what was up with that??  we had it first :))).
Renamed "SceneObject" to "Node".  Shorter to type :), and a little more clear for those knowledgeable in scene graphs.

The functionality is the same as GearVRf.

We will continue to provide bugfixes for GearVRf, but all new development from this point will be with the SXR SDK.

**Comment by spakanati123** [comment]
Thanks for the update @thomasflynn

**Comment by spakanati123** [comment]
@thomasflynn when i am building with com.samsungxr:sxrsdk still i am getting does n't found, what is expected deployment to maven?
The version i used : 4.0.1-SNAPSHOT

**Comment by joturako** [comment]
I'm closing this issue since `release_v5.0` have appeared.
