### ISSUE TITLE
camera not enabled on monoscopic various

### ISSUE THREAD

**Issue by kismeter** [sxrsdk/sxrsdk-demos#73]
when change the build various mode to monoscopic, launcher the APP, show "move around to find a horizontal surface" with black screen. no camera preview come to the screen.

**Comment by liaxim** [comment]
@kismeter Which demo app are you referring to? Some apps do not request the camera permission at runtime so you have to manually grant it.

**Comment by kismeter** [comment]
@liaxim I mean the demo app sxr-arpet, I give the camera permission to that app.

**Comment by liaxim** [comment]
@kismeter Grant also the storage permission manually.

**Comment by liaxim** [comment]
PR: https://github.com/sxrsdk/sxrsdk-demos/pull/74

**Comment by liaxim** [comment]
@kismeter Assuming it is all good now. Let us know if otherwise.
