### ISSUE TITLE
trouble in run demos

### ISSUE THREAD

**Issue by zhuxiaol** [sxrsdk/sxrsdk-demos#82]
1. Which demo use camera to preview?
2. sxr-arcore cannot work well. When I run sxr-arcore, the phone is black.

**Comment by liaxim** [comment]
@zhuxiaol Please manually grant the Camera permission to the app, force-stop it and launch again.

**Comment by zhuxiaol** [comment]
> 
> 
> @zhuxiaol Please manually grant the Camera permission to the app, force-stop it and launch again.

Actually, I have done what you say before I comment the issue. Camera permission is OK. Force-stop the app and launch again. But only a purple line is shown. The purple line is changed when the phone is moved. Can you share me what the app is correctly shown.

**Comment by zhuxiaol** [comment]
@liaxim 
Actually, I have done what you say before I comment the issue. Camera permission is OK. Force-stop the app and launch again. But only a purple line is shown. The purple line is changed when the phone is moved. Could you share me what the app is correctly shown?

**Comment by liaxim** [comment]
@zhuxiaol Hi. What device are you using? What Android version?

**Comment by zhuxiaol** [comment]
@liaxim 
Device: Galaxy S8+
Android version: 8.0.0

VR-related apps can work well. The sxr-blurfilter demo with camera previews works well too. Only ar-related apps such as sxr-arcore and sxr-aravatar cannot work well as I mention above.

**Comment by liaxim** [comment]
@zhuxiaol Can you share a screenshot or two? Thanks.

**Comment by zhuxiaol** [comment]
@liaxim My sxr-arcore shows a purple line. The purple line is changed when camera moved.
![Screenshot_20190424-095304_sxr-arcore-simplesample-monoscopic](https://user-images.githubusercontent.com/49772251/56627103-086ccc00-6677-11e9-871a-44d956b0ae78.jpg)
![Screenshot_20190424-095704_sxr-arcore-simplesample-monoscopic](https://user-images.githubusercontent.com/49772251/56627205-639ebe80-6677-11e9-8142-9b13893bec86.jpg)

**Comment by liaxim** [comment]
@zhuxiaol Thanks. This is rather weird. Can you possibly share the logcat output too?

**Comment by liaxim** [comment]
@zhuxiaol Do you have an update for us?

**Comment by liaxim** [comment]
Unfortunately without logs I don't know where to start from. Please reopen if you are able to give us more information.
